### Insert player and goalie statistics into MySQL tables

In [1]:
# Packages
import pandas as pd
import sqlalchemy
from MySQLClass import MySQL

In [2]:
# User input
# skater_path = '/Volumes/LUNANI/sports_betting_csv_backup/game_stats/skater_games.csv'
# goalies_path = '/Volumes/LUNANI/sports_betting_csv_backup/game_stats/goalie_games.csv'

skater_path = '/Users/bryanmichalek/Documents/GitHub_Personal/sports_betting_data/data/historic_batch/stats/skater.csv'
goalies_path = '/Users/bryanmichalek/Documents/GitHub_Personal/sports_betting_data/data/historic_batch/stats/goalie.csv'

In [3]:
# Create the engine to connect to the MySQL database
mysql = MySQL()
mysql.connect()

### Skaters

In [4]:
# Read in CSV files
skater = pd.read_csv(skater_path)
display(skater.head())

,player_id,player_name,age,season,game_num,date,team,opponent,home_away_status,result,...,SHA,S,S_perc,shifts,TOI,HIT,BLK,FOW,FOL,FOW_perc
0,abdelju01,justin abdelkader,31,2019,1,2018-10-04,DET,CBJ,1.0,L-OT,...,0,0,NaN,25,16.116667,1,0.0,1.0,0.0,100.0
1,abdelju01,justin abdelkader,31,2019,2,2018-10-07,DET,LAK,0.0,L,...,0,1,0.0,25,17.283333,0,1.0,4.0,2.0,66.7
2,abdelju01,justin abdelkader,31,2019,3,2018-10-08,DET,ANA,0.0,L-SO,...,0,0,NaN,19,12.616667,0,1.0,3.0,4.0,42.9
3,abdelju01,justin abdelkader,31,2019,4,2018-10-11,DET,TOR,1.0,L,...,0,0,NaN,21,13.566667,4,0.0,0.0,1.0,0.0
4,abdelju01,justin abdelkader,31,2019,5,2018-10-13,DET,BOS,0.0,L,...,0,2,0.0,21,15.300000,2,0.0,2.0,0.0,100.0

In [5]:
# Select the correct columns, rename, and order them
skater = skater[['player_id', 'team', 'game_num', 'date', 'opponent', 'G', 'A', 'P', 'rating', 'PIM', 'EVG', 'PPG', 'SHG', 'GWG', 'EVA', 'PPA', 'SHA', 'S', 'S_perc', 'shifts', 'TOI', 'HIT', 'BLK', 'FOW', 'FOL', 'FOW_perc']].rename(columns={'S_perc':'S_pct', 'FOW_perc':'FOW_pct'})

In [7]:
# Insert into skater statistics table
skater.to_sql(name = 'skater_game', con=mysql.engine, schema='nhl', if_exists='append', index=False)

-1

In [24]:
# Empty the df
#skater = skater.iloc[0:0]
#skater.to_csv(skater_path, header=True, index=False)

### Goalies

In [8]:
# Read in CSV files
goalie = pd.read_csv(goalies_path)
display(goalie.head())

,player_id,player_name,age,season,game_num,date,team,opponent,home_away_status,result,decision,GA,SA,SV,SV_perc,shutout,PIM,TOI
0,allenja01,jake allen,28,2019,1,2018-10-04,STL,WPG,1,L,L,5,25,20,0.800,0,0,60.000000
1,allenja01,jake allen,28,2019,2,2018-10-06,STL,CHI,1,L-OT,O,5,30,25,0.833,0,0,62.166667
2,allenja01,jake allen,28,2019,3,2018-10-11,STL,CGY,1,W,W,3,34,31,0.912,0,0,60.000000
3,allenja01,jake allen,28,2019,4,2018-10-13,STL,CHI,0,L-OT,O,4,50,46,0.920,0,0,64.783333
4,allenja01,jake allen,28,2019,5,2018-10-17,STL,MTL,0,L,L,3,23,20,0.870,0,0,59.766667

In [9]:
# Select the correct columns, rename, and order them
goalie = goalie[['player_id', 'team', 'game_num', 'date', 'opponent', 'decision', 'GA', 'SA', 'SV', 'SV_perc', 'shutout', 'PIM', 'TOI']].rename(columns={'SV_perc':'SV_pct'})

In [10]:
# Insert into goalie statistics table
goalie.to_sql(name = 'goalie_game', con=mysql.engine, schema='nhl', if_exists='append', index=False)

-1

In [ ]:
# Empty the df
#goalie = goalie.iloc[0:0]
#goalie.to_csv(goalie_path, header=True, index=False)